BookRepo = 'https://github.com/mikage-emu/3dbrew'
BookEditPath = 'edit/main'
BookLogo = '3dbrew2.png'
BookViewPath = 'blob/main'
BookViewSuffix = '?plain=1'

[article]
readingTime = false

[[widgets.homepage]]
type = "categories"

[[widgets.page]]
type = "toc"

[sidebar.avatar]
src = "3dbrew2.png"
